# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_name', models.CharField(max_length=20, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('file_status', models.BooleanField(default=False)),
                ('tree_path', models.CharField(blank=True, max_length=100, null=True)),
                ('png_path', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
