# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='classify',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
