# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0002_tree_classify'),
    ]

    operations = [
        migrations.CreateModel(
            name='towK',
            fields=[
                ('kid', models.AutoField(primary_key=True, serialize=False)),
                ('dataName', models.CharField(max_length=20, unique=True)),
                ('clusterNum', models.IntegerField()),
                ('pngPath', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
