# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine', '0003_towk'),
    ]

    operations = [
        migrations.AddField(
            model_name='towk',
            name='file_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
